- hosts: localhost
  tasks:
  - name: create_mac_var
    set_fact:
     mac: "{{ansible_default_ipv4.macaddress.split(':')}}"
  
  - name: create_test
    debug: 
     msg: test {{mac}} {{ansible_default_ipv4.macaddress}} cmp-{{mac[4]}}{{mac[5]}} {{inventory_hostname}}
  
  - name: mesg_with_items
    debug: 
     msg: module {{item.src}}
    with_items:
    - {src: 'a', dest: 'dst_a'} 
    - {src: 'b', dest: 'dst_b'}
  
