 
###### INSTALL CONFS FILES ##### 
- name: copy OS keystone confs
  template:
   dest: /etc/keystone/keystone.conf
   src: templates/keystone.j2
  tags: keystone, os

- name: copy OS glance confs
  template:
   src: "{{item.src}}"
   dest: "{{item.dest}}"
   backup: yes
  with_items:
   - {src: 'glance-api.j2', dest: '/etc/glance/glance-api.conf'}
   - {src: 'glance-registry.j2', dest: '/etc/glance/glance-registry.conf'}
  tags: glance, os
   
- name: copy OS keystone confs
  template:
   dest: /etc/nova/nova.conf
   src: templates/nova.j2
  tags: nova, os

