---
- name: add all db
  mysql_db:
   name: "{{item}}"
   state: present
  with_items:
   - keystone
   - nova
   - nova_api
   - neutron
   - glance
  tags: db
  
- name: add all os users to locahost
  mysql_user:
   name: "{{item.user}}"
   password: "{{global_os_password}}"
   priv: '{{item.db}}.*:ALL'
   host: localhost
   state: present
   append_privs: yes
  with_items:
   - {user: 'nova', db: 'nova'}
   - {user: 'nova', db: 'nova_api'}
   - {user: 'keystone', db: 'keystone'}
   - {user: 'neutron', db: 'neutron'}
   - {user: 'glance', db: 'glance'}
  tags: db

- name: add all os users to %
  mysql_user:
   name: "{{item.user}}"
   password: "{{global_os_password}}"
   priv: '{{item.db}}.*:ALL'
   host: '%'
   state: present
   append_privs: yes
  with_items:
   - {user: 'nova', db: 'nova'}
   - {user: 'nova', db: 'nova_api'}
   - {user: 'keystone', db: 'keystone'}
   - {user: 'neutron', db: 'neutron'}
   - {user: 'glance', db: 'glance'}
  tags: db

