---
- name: add all db
  mysql_db:
   name: "{{item}}"
   state: present
  with_items:
   - keystone
   - nova
   - nova_api
   - neutron
   - glance
  tags: db
  
- name: add all os users to locahost
  mysql_user:
   name: "{{item.user}}"
   password: "{{global_os_password}}"
   priv: '{{item.db}}.*:ALL'
   host: localhost
   state: present
   append_privs: yes
  with_items:
   - {user: 'nova', db: 'nova'}
   - {user: 'nova', db: 'nova_api'}
   - {user: 'keystone', db: 'keystone'}
   - {user: 'neutron', db: 'neutron'}
   - {user: 'glance', db: 'glance'}
  tags: db

- name: add all os users to %
  mysql_user:
   name: "{{item.user}}"
   password: "{{global_os_password}}"
   priv: '{{item.db}}.*:ALL'
   host: '%'
   state: present
   append_privs: yes
  with_items:
   - {user: 'nova', db: 'nova'}
   - {user: 'nova', db: 'nova_api'}
   - {user: 'keystone', db: 'keystone'}
   - {user: 'neutron', db: 'neutron'}
   - {user: 'glance', db: 'glance'}
  tags: db

- name: activate dbs
  command: "{{item}}"
  with_items:
   - su -s /bin/sh -c "keystone-manage db_sync" keystone
   - su -s /bin/sh -c "glance-manage db_sync" glance
   - su -s /bin/sh -c "nova-manage api_db sync" nova
   - su -s /bin/sh -c "nova-manage db sync" nova
   - su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  tags: db
