---
- name: test_token
  debug: msg={{global_admin_token}}

- name: create_controller_hostname
  hostname:
   name: "{{inventory_hostname}}"

- name: add mitaka repo
  yum_repository:
   name: os-mitaka
   description: os-mitaka
   baseurl: http://vault.centos.org/centos/7.2.1511/cloud/x86_64/openstack-mitaka/
   gpgcheck: 0
   enabled: 0
   state: present

- name: install mariadb & httpd & mod_wsgi
  yum:
   name: 
   - mariadb
   - mariadb-server
   - httpd 
   - mod_wsgi
   state: latest
  
 
- name: install OS nova components
  yum:
   enablerepo: os-mitaka 
   name:
   - openstack-nova-api
   - openstack-nova-conductor
   - openstack-nova-console 
   - openstack-nova-novncproxy
   - openstack-nova-scheduler
   state: latest
  tags: nova, os  

- name: install OS neutron components
  yum:
   enablerepo: os-mitaka 
   name:
   - openstack-neutron
   - openstack-neutron-ml2
   - openstack-neutron-linuxbridge 
   - ebtables 
   state: latest
  tags: neutron, os

- name: install OS glance
  yum:
   enablerepo: os-mitaka 
   name:
   - openstack-glance
   state: latest
  tags: glance, os

- name: install OS keystone 
  yum: 
   enablerepo: os-mitaka 
   name:
   - openstack-keystone
   state: latest
  tags: keystone, os


- name: install helpfull pkgs
  yum:
   enablerepo: os-mitaka 
   name:
   - rabbitmq-server
   - python-openstackclient
   - python2-PyMySQL
   - python-memcached
   - memcached
   state: latest
  tags: os



 
#- name: install OS components
