---

- name: create OS services
  environment:
   OS_TOKEN: "{{global_admin_token}}"
   OS_URL: "http://controller:35357/v3"
   OS_AUTH_URL: "http://controller:35357/v3"
   OS_IDENTITY_API_VERSION: 3
   OS_AUTH_TYPE: admin_token
  command:  "openstack service create --name {{item.name}} --description {{item.descr}} {{item.service}}"
   #command:  "env"
  with_items:
   - "{{global_os_services}}"
  tags: services, endpoints

- name: create OS public enpoint
  environment:
   OS_TOKEN: "{{global_admin_token}}"
   OS_AUTH_URL: http://controller:35357/v3
   OS_IDENTITY_API_VERSION: 3
   OS_AUTH_TYPE: admin_token
  command: "openstack endpoint create --region RegionOne {{item.service}} public http://controller:5000/v3"
  with_items:
   - "{{global_os_services}}"
  tags: services, endpoints

- name: create OS internal enpoint
  environment:
   OS_TOKEN: "{{global_admin_token}}"
   OS_AUTH_URL: http://controller:35357/v3
   OS_IDENTITY_API_VERSION: 3
   OS_AUTH_TYPE: admin_token
  command: "openstack endpoint create --region RegionOne {{item.service}} internal http://controller:5000/v3"
  with_items:
   - "{{global_os_services}}"
  tags: services, endpoints

- name: create OS admin ednpoint
  environment:
   OS_TOKEN: "{{global_admin_token}}"
   OS_AUTH_URL: http://controller:35357/v3
   OS_IDENTITY_API_VERSION: 3
   OS_AUTH_TYPE: admin_token
  command: "openstack endpoint create --region RegionOne {{item.service}} admin http://controller:35357/v3"
  with_items:
   - "{{global_os_services}}"
  tags: services, endpoints




