---
- name: start and enable rabbitmq
  service:
   name: rabbitmq-server
   enabled: yes
   state: started
  tags: rabbit

- name: rabbitmq add user
  rabbitmq_user:
   user: openstack
   password: "{{global_os_password}}"
   permissions:
   - vhost: /
     configure_priv: .*
     read_priv: .*
     write_priv: .*
   state: present
  tags: rabbit

